main: ${group}.${pluginName}
name: ${pluginName}
version: ${pluginVersion}
description: ${pluginDescription}
authors:
  - tomwmth
  - BestBearr
  - Crystal Development, LLC.
website: ${pluginWebsite}
api-version: 1.13

softdepend:
  - Vault
  - PlaceholderAPI