main: co.crystaldev.alpinecore.AlpineCore
name: AlpineCore
version: "${version}"
description: "${description}"
api-version: 1.13
website: https://github.com/alpine-network/alpine-core
authors:
  - tomwmth
  - BestBearr
  - Crystal Development, LLC.
softdepend:
  - Vault
  - PlaceholderAPI
