name: "Deploy Snapshot"

on:
  push:
    branches: [master]

jobs:
  build_deploy_snapshot:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: "Checkout source"
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Set up JDK"
        # https://github.com/actions/setup-java/releases
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: temurin
          java-version: 17

      - name: "Setup Gradle"
        # https://github.com/gradle/actions/releases
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          validate-wrappers: true
          gradle-version: wrapper
          cache-disabled: false

      - name: "Build artifacts"
        run: ./gradlew build -Psnapshot=true --full-stacktrace

      - name: "Publish artifacts"
        run: ./gradlew publish -Psnapshot=true --full-stacktrace
        env:
          ALPINE_MAVEN_NAME: ${{ secrets.ALPINE_MAVEN_NAME }}
          ALPINE_MAVEN_SECRET: ${{ secrets.ALPINE_MAVEN_SECRET }}
