main: co.crystaldev.alpinecore.AlpineCore
name: AlpineCore
version: "${version}"
description: "${description}"
api-version: "1.21"
website: https://github.com/alpine-network/alpine-core
authors:
  - tomwmth
  - BestBearr
  - Crystal Development, LLC.
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
